version: '3.7'  # Upgraded to a newer version for healthcheck support
services:
  backend:
    image: lakshya545/myflask:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=mydb
    depends_on:
      mysql:
        condition: service_healthy  # Waits until MySQL is healthy

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    healthcheck:  # Adding health check for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

